### PR TITLE
Support expires values larger than the maximum date

### PR DESCRIPTION
**Pull request by akh9804**
`Expires` should work even when it is above **the maximum date**

### CODE REVIEW

**Comment by theodorejb** [comment]
What is the use case for this? Can you show a code example where it would be useful?

**Comment by theodorejb** [comment]
Why not set `expires` to a less insanely large number? E.g. even if you just set it to `100_000` that would be enough for the cookie to not expire for hundreds of years.

**Comment by akh9804** [comment]
You're right. But I didn't know until I looked into source code that the error was due to the large value I put in. I think this one is necessary to prevent this situation.

**Review by theodorejb — APPROVED** [review]
Thank you!

**Pull request merged**
